services:
  dzarsky.todoapptemplate.api:
    image: dzarsky.todoapptemplate.api
    depends_on:
        - db
    build:
      context: .
      dockerfile: DZarsky.ToDoAppTemplate.Api/Dockerfile
    links:
      - "db:postgres"
    ports:
        - "31255:8080"
        - "31256:8081"
  db:
    image: postgres:15-alpine3.19
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: TOD0app24
      POSTGRES_DB: todoapp
    ports:
        - "54321:5432"
    volumes:
      - pgdata-todoapp:/var/lib/postgresql/data
volumes:
  pgdata-todoapp:
