name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Create migration bundle
        run: |
          export PATH="$PATH:/root/.dotnet/tools" && \
          dotnet ef migrations bundle --startup-project DZarsky.ToDoAppTemplate.Api/DZarsky.ToDoAppTemplate.Api.csproj \
          --project DZarsky.ToDoAppTemplate.Data/DZarsky.ToDoAppTemplate.Data.csproj --self-contained -r linux-x64 \
          --output publish/efbundle
      - name: Publish
        run: dotnet publish --no-restore --configuration Release --output publish/app
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ToDoAppTemplate
          path: publish
