name: Docker

on:
  push:
    branches: ["master"]
    tags: ["v*.*.*"]

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - if: ${{ startsWith(github.ref, 'refs/tags/')}}
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: ${{ startsWith(github.ref, 'refs/tags/')}}
          file: ToDoAppTemplate.Api/Dockerfile
          tags: |
            loupeznik/todo-app-template:${{ github.ref_name }}
            loupeznik/todo-app-template:latest
